name: 'verify-build'

on:
  push:
    branches:
      - custombuild

defaults:
  run:
    shell: bash

jobs:
  maven:
    name: 'maven-build'
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to the GitHub Actions runner
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Maven
        run: bin/mvn-deploy-github.sh
        env:
          GH_REPO: ${{ env.GITHUB_REPOSITORY }}
          GH_DEPLOY_USERNAME: ${{ env.GITHUB_REPOSITORY_OWNER }}
          GH_DEPLOY_TOKEN: ${{ secrets.GITHUB_TOKEN }}